### ISSUE TITLE
"Could not GET" is matched case-insensitively

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/steps-gradle-runner#74] opened 2020-06-04 11:10 UTC
There seems to be a feature to rerun step on failure if some particular texts are present in log.
One of those is "Could not GET". This is exactly how it is written:
https://github.com/bitrise-steplib/steps-gradle-runner/blob/e19792c015eb4b2dd3650f32c63eaf29b8c30d2c/main.go#L29

However it seems to be matched case-insensitively instead of sensitively. This leads to unneeded retries of builds containing texts like: `Could not get the name for org_koin__koin_androidx_scope, Using org.koin:koin-androidx-scope` which are normally produced by AboutLibraries Gradle plugin.

**Comment by non-binary** [comment] 2020-06-04 13:02
Hi @koral--,

I've created a JIRA ticket for the engineering team to look at this. I don't know when they will because they control their own sprints but it is in their backlog.

**Comment by koral--** [comment] 2020-06-05 17:07
Thanks @non-binary.

BTW I've reported the same issue via zendesk (request 2838), you were also in one of the threads. However, that ticket enters some weird state, eg. support access has expired few times, zendesk keeps sending "Automatic reply reason is needed" messages to me despite that reply was only needed from Bitrise staff etc.

**Comment by non-binary** [comment] 2020-06-05 20:11
Hi @koral--,

Sorry for the hassle. It seems that Zendesk ticket was closed due to inactivity. We never received your response in disabling and re-enabling support access so the ticket closed. Rest assured however, this will be looked at by the tooling team soon.

**Comment by koral--** [comment] 2020-06-05 20:34
OK.
My last message was sent to support+id2838@bitrise.zendesk.com on May 13th along with re-enabled support access.
This is at least 2nd zendesk ticket which have similar problem. Maybe I'll create a ticket about that 🤔

**Comment by non-binary** [comment] 2020-06-05 22:10
Hi @koral--,

Please send me an email at luna.graysen@bitrise.io and I'll investigate it further with you next week (already off for the weekend). We had another customer that we weren't receiving emails from.

Have a nice weekend!

**Comment by koral--** [comment] 2021-02-14 22:19
@godrei @mjones-droid (I mention you as 2 last users active in this issue tracker).
What is the status of the main issue and follow-up from the last reply?
It seems that @non-binary does no longer work for Bitrise.

**Comment by mjones-droid** [comment] 2021-02-16 14:39
Hey @koral--,

You are correct. @non-binary has moved on from Bitrise to another amazing opportunity. I did check the status of the bug and it appears to still be in the backlog. I'll ping the dev's and ask for an update. 

Matthew
Senior Customer Engineer

**Comment by koral--** [comment] 2021-02-16 15:47
@mjones-droid keep note that there are 2 issues here.
1st one reported in the 1st post - Could not GET...
And 2nd about zendesk issues while trying to report tickets which was discussed with @non-binary by e-mail. Let me know if I should forward those messages to some other address or you can access their inbox archive.

**Comment by mjones-droid** [comment] 2021-02-16 15:56
Hey @koral--,

We're in the process of making a major change to the way ZenDesk tickets are reported. Hopefully this will resolve any issues you were having.

**Comment by mjones-droid** [comment] 2021-02-24 16:07
Hey @koral--

As I said, we're making some major changes to our ZenDesk config. I've sent you an email to the address on your GitHub page. If you could forward me the correspondence you had with @non-binary that would be helpful.

**Comment by koral--** [comment] 2021-02-24 16:39
Done, thanks.

**Comment by koral--** [comment] 2021-05-26 14:27
still important to me

**Comment by Roland-Bak** [comment] 2021-06-08 11:47
Hey @koral-- 

Thanks for the confirmation, I can confirm that we are still working on this 🙂

**Comment by lpusok** [comment] 2021-07-13 12:27
Hello @koral-- ,
Fixed in https://github.com/bitrise-steplib/steps-gradle-runner/releases/tag/2.0.0. Decided to remove the automatic retry as Gradle 5+ does include HTTP retries for resources.

**Closed by lpusok** 2021-07-13 12:27 UTC
